# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

parameters:
  - name : "Test_Suite"
    displayName: "Select which suite to run"
    type: string
    default: 'smoke'

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: pip install -r requirements.txt
  displayName: "Install dependencies"

- script: |
    pytest -m ${{parameters.Test_Suite}} --junitxml=$(Build.ArtifactStagingDirectory)/smoke.xml
  displayName: 'Run pytest tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*.xml'
    testRunTitle: 'Tests: ${{parameters.Test_Suite}}'
  condition: always()
